ccflags-y += -Idrivers/media/platform/msm/camera_v2-tb8703
ccflags-y += -Idrivers/media/platform/msm/camera_v2-tb8703/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-tb8703/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-tb8703/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
