ccflags-y += -Idrivers/media/platform/msm/camera_v2-tb8703
ccflags-y += -Idrivers/media/platform/msm/camera_v2-tb8703/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-tb8703/sensor/io
obj-$(CONFIG_MSM_CSIPHY) += msm_csiphy.o
