ccflags-y += -Idrivers/media/platform/msm/camera_v2-tb8703
ccflags-y += -Idrivers/media/platform/msm/camera_v2-tb8703/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2-tb8703/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-tb8703/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-tb8703/msm_buf_mgr/
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
